### ISSUE TITLE
Script doesn't account for '/'

### ISSUE THREAD

**Issue by Kameecoding** [pearu/ftpsync2d#8]
`listing directory '/temp/' <connecting to 178.63.32.185..
<creating directory '/temp'>Traceback (most recent call last):
  File "ftpsync2d/ftpsync.py", line 709, in <module>
    main()
  File "ftpsync2d/ftpsync.py", line 618, in main
    remote_files = session.get_files(update_listing=options.update_listing)
  File "ftpsync2d/ftpsync.py", line 322, in get_files
    for rfn, mtime in self.get_remote_files(update_listing=update_listing).items():
  File "ftpsync2d/ftpsync.py", line 239, in get_remote_files
    lst = filter(lambda n: n not in ['.', '..'], self.ftp.nlst(wd))
  File "ftpsync2d/ftpsync.py", line 131, in ftp
    self.clock_offset = self.clocksync()
  File "ftpsync2d/ftpsync.py", line 174, in clocksync
    self.makedirs(os.path.dirname(rfn))
  File "ftpsync2d/ftpsync.py", line 378, in makedirs
    self.ftp.mkd(fullpath)
  File "/usr/lib/python2.7/ftplib.py", line 577, in mkd
    resp = self.sendcmd('MKD ' + dirname)
  File "/usr/lib/python2.7/ftplib.py", line 249, in sendcmd
    return self.getresp()
  File "/usr/lib/python2.7/ftplib.py", line 224, in getresp
    raise error_perm, resp
ftplib.error_perm: 550 Create directory operation failed.
`

Here is `lst` printed out from line 371 
`['/Desktop', '/Downloads', '/acd', '/cleanup.sh', '/conv2mp4-py.py', '/download.sh', '/downlooad.sh', '/encfs.xml', '/ftpsync2d', '/home', '/launcher.sh', '/local', '/media', '/simple_convert.log', '/sync.sh', '/temp']`

It failes because it tries to find 'temp' but the list only containst '/temp'

**Comment by pearu** [comment]
I wonder, what is the value of `parent` when error is raised, is it `'/'`? Perhaps, more universal check would be `parent=='/'` instead of checking the content of `lst`?

In any case, I merged your patch with the trunk. Thanks!

**Comment by Kameecoding** [comment]
Indeed parent == '/'
